# States for ConversationHandler
(
    MAIN_MENU,
    MAIN_MENU_ADMIN,
    SINGLE_POLL_NAME,
    SINGLE_POLL_LAST_NAME,
    SINGLE_POLL_NICK,
    SINGLE_POLL_MMR,
    SINGLE_POLL_ROLES,
    SINGLE_POLL_DOTABUFF,
    SINGLE_POLL_TG,
    SINGLE_POLL_AGREEMENT,
    MULTI_POLL_COUNT,
    MULTI_POLL_CURRENT_NAME,
    MULTI_POLL_CURRENT_AGE,
    CHECK_SUBSCRIPTION
) = range(14)

user_data = {}